version: "3.7"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/usr/src/app"
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    command: python manage.py run -h 0.0.0.0
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 4200:4200
    depends_on:
      - server
